version: '3.9'

services:
  db_dev:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: db_dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]

    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:${PGDATA}

volumes:
  pgdata: {}
