class Formater {
    public advanceTransformer(
        data: {
            id: number;
            vToDS: {
                id: number;
                vendor: { id: number; name: string };
                dealerSite: {
                    id: number;
                    name: string;
                    dealer: { id: number; name: string };
                };
            };
            buyerSite: {
                id: number;
                name: string;
                buyer: {
                    id: number;
                    name: string;
                };
            };
        }[]
    ) {
        let cur = data[0];

        const curVendor = cur.vToDS.vendor.name;
        const curDealer = cur.vToDS.dealerSite.dealer.name;
        const curDealerSite = cur.vToDS.dealerSite.name;
        const curBuyer = cur.buyerSite.buyer.name;
        const curBuyerSite = cur.buyerSite.name;

        let temp: Record<string, any> = {};

        if (data.length == 1) {
            temp = {
                ...temp,
                [cur.vToDS.vendor.name]: {
                    name: cur.vToDS.vendor.name,
                    id: cur.vToDS.vendor.id,
                    dealer: {
                        [cur.vToDS.dealerSite.dealer.name]: {
                            name: cur.vToDS.dealerSite.dealer.name,
                            id: cur.vToDS.dealerSite.dealer.id,
                            [cur.vToDS.dealerSite.name]: {
                                name: cur.vToDS.dealerSite.name,
                                id: cur.vToDS.dealerSite.id,
                            },
                        },
                    },
                    buyer: {
                        [cur.buyerSite.buyer.name]: {
                            name: cur.buyerSite.buyer.name,
                            id: cur.buyerSite.buyer.name,
                            [cur.buyerSite.name]: {
                                name: cur.buyerSite.name,
                                id: cur.buyerSite.id,
                            },
                        },
                    },
                },
            };
        }
        for (let i = 1; i < data.length; i++) {
            let next = data[i];
            if (curVendor === next.vToDS.vendor.name) {
                if (curDealer === next.vToDS.dealerSite.dealer.name) {
                    if (curDealerSite === next.vToDS.dealerSite.name) {
                        // do nothing;
                    } else {
                        temp = {
                            ...temp,
                            [curVendor]: {
                                ...temp[curVendor],
                                dealer: {
                                    [curDealer]: {
                                        ...temp[curDealer],
                                        [next.vToDS.dealerSite.name]: {
                                            name: next.vToDS.dealerSite.name,
                                            id: next.vToDS.dealerSite.id,
                                        },
                                    },
                                },
                            },
                        };
                    }
                }

                if (curDealer !== next.vToDS.dealerSite.dealer.name) {
                    temp = {
                        ...temp,
                        [curVendor]: {
                            ...temp[curVendor],
                            dealer: {
                                [next.vToDS.dealerSite.dealer.name]: {
                                    name: next.vToDS.dealerSite.dealer.name,
                                    id: next.vToDS.dealerSite.dealer.id,
                                },
                            },
                        },
                    };
                }

                if (curBuyer === next.buyerSite.buyer.name) {
                    if (curBuyerSite === next.buyerSite.name) {
                        // do nothing;
                    } else {
                        temp = {
                            ...temp,
                            buyer: {
                                [curBuyer]: {
                                    ...temp[curBuyer],
                                    [next.buyerSite.name]: {
                                        name: next.buyerSite.name,
                                        id: next.buyerSite.id,
                                    },
                                },
                            },
                        };
                    }
                }

                if (curBuyer !== next.buyerSite.buyer.name) {
                    temp = {
                        ...temp,
                        [curVendor]: {
                            ...temp[curVendor],
                            buyer: {
                                [next.buyerSite.buyer.name]: {
                                    name: next.buyerSite.buyer.name,
                                    id: next.buyerSite.buyer.id,
                                },
                            },
                        },
                    };
                }
            } else {
                temp = {
                    ...temp,
                    [cur.vToDS.vendor.name]: {
                        name: cur.vToDS.vendor.name,
                        id: cur.vToDS.vendor.id,
                        dealer: {
                            [cur.vToDS.dealerSite.dealer.name]: {
                                name: cur.vToDS.dealerSite.dealer.name,
                                id: cur.vToDS.dealerSite.dealer.id,
                                [cur.vToDS.dealerSite.name]: {
                                    name: cur.vToDS.dealerSite.name,
                                    id: cur.vToDS.dealerSite.id,
                                },
                            },
                        },
                        buyer: {
                            [cur.buyerSite.buyer.name]: {
                                name: cur.buyerSite.buyer.name,
                                id: cur.buyerSite.buyer.name,
                                [cur.buyerSite.name]: {
                                    name: cur.buyerSite.name,
                                    id: cur.buyerSite.id,
                                },
                            },
                        },
                    },
                };
            }
            cur = next;
        }

        return temp;
    }
}

const formater = new Formater();

const obj = [
    {
        id: 29,
        updated_at: "2022-10-31T03:16:47.181Z",
        created_at: "2022-10-31T03:16:47.181Z",
        start_date: null,
        end_date: null,
        buyerSiteId: 4,
        vds_rltn_id: 1,
        buyerSite: {
            id: 4,
            updated_at: "2022-10-30T16:21:39.163Z",
            created_at: "2022-10-30T16:21:39.163Z",
            start_date: null,
            end_date: null,
            name: "Zulauf-Zulauf",
            attribute1: null,
            attribute2: null,
            attribute3: null,
            attribute4: null,
            attribute5: null,
            externalVCode: "gsmcfalvpx",
            externalDSCode: "qvsjjznwvu",
            externalBSCode: "ut",
            buyer_id: 18,
            buyer: {
                id: 18,
                updated_at: "2022-10-30T16:21:34.367Z",
                created_at: "2022-10-30T16:21:34.367Z",
                start_date: null,
                end_date: null,
                name: "Harmony",
                taxNo: "32947299977",
                attribute1: null,
                attribute2: null,
                attribute3: null,
                attribute4: null,
                attribute5: null,
            },
        },
        vToDS: {
            id: 1,
            updated_at: "2022-10-30T16:21:39.179Z",
            created_at: "2022-10-30T16:21:39.179Z",
            start_date: null,
            end_date: null,
            vendorId: 18,
            dealerSiteId: 18,
            dealerSite: {
                id: 18,
                updated_at: "2022-10-30T16:21:39.125Z",
                created_at: "2022-10-30T16:21:39.125Z",
                start_date: null,
                end_date: null,
                name: "Sylvan Ruecker",
                attribute1: null,
                attribute2: null,
                attribute3: null,
                attribute4: null,
                attribute5: null,
                externalVCode: "gsmcfalvpx",
                externalDSCode: "qvsjjznwvu",
                dealerId: 18,
                dealer: {
                    id: 18,
                    updated_at: "2022-10-30T16:21:35.177Z",
                    created_at: "2022-10-30T16:21:35.177Z",
                    start_date: null,
                    end_date: null,
                    name: "Maria",
                    taxNo: "87880637031",
                    attribute1: null,
                    attribute2: null,
                    attribute3: null,
                    attribute4: null,
                    attribute5: null,
                },
            },
            vendor: {
                id: 18,
                updated_at: "2022-10-30T16:21:31.692Z",
                created_at: "2022-10-30T16:21:31.692Z",
                start_date: null,
                end_date: null,
                name: "Mr. Deven Bahringer II",
                taxNo: "26326929848",
                attribute1: null,
                attribute2: null,
                attribute3: null,
                attribute4: null,
                attribute5: null,
                externalVCode: "gsmcfalvpx",
            },
        },
    },
    // },
    // {
    //     id: 36,
    //     updated_at: "2022-10-31T03:20:00.231Z",
    //     created_at: "2022-10-31T03:20:00.231Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 12,
    //     vds_rltn_id: 14,
    //     buyerSite: {
    //         id: 12,
    //         updated_at: "2022-10-30T16:21:48.113Z",
    //         created_at: "2022-10-30T16:21:48.113Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Raynor Ltd",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "ipgmlzpzgq",
    //         externalDSCode: "jvuujdgagp",
    //         externalBSCode: "hic",
    //         buyer_id: 48,
    //         buyer: {
    //             id: 48,
    //             updated_at: "2022-10-30T16:21:47.957Z",
    //             created_at: "2022-10-30T16:21:47.957Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Vicky",
    //             taxNo: "26963081411",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 14,
    //         updated_at: "2022-10-30T16:22:21.933Z",
    //         created_at: "2022-10-30T16:22:21.933Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 34,
    //         dealerSiteId: 34,
    //         dealerSite: {
    //             id: 34,
    //             updated_at: "2022-10-30T16:21:48.089Z",
    //             created_at: "2022-10-30T16:21:48.089Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Olin Wintheiser",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ipgmlzpzgq",
    //             externalDSCode: "jvuujdgagp",
    //             dealerId: 48,
    //             dealer: {
    //                 id: 48,
    //                 updated_at: "2022-10-30T16:21:45.282Z",
    //                 created_at: "2022-10-30T16:21:45.282Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Benton",
    //                 taxNo: "69776156990",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 34,
    //             updated_at: "2022-10-30T16:21:37.386Z",
    //             created_at: "2022-10-30T16:21:37.386Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Destany Olson",
    //             taxNo: "40665066597",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ipgmlzpzgq",
    //         },
    //     },
    // },
    // {
    //     id: 30,
    //     updated_at: "2022-10-31T03:17:14.411Z",
    //     created_at: "2022-10-31T03:17:14.411Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 15,
    //     vds_rltn_id: 3,
    //     buyerSite: {
    //         id: 15,
    //         updated_at: "2022-10-30T16:21:51.954Z",
    //         created_at: "2022-10-30T16:21:51.954Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Mayer-Mayer",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "nhkflvsvzm",
    //         externalDSCode: "hguvozryla",
    //         externalBSCode: "quis",
    //         buyer_id: 7,
    //         buyer: {
    //             id: 7,
    //             updated_at: "2022-10-30T16:21:26.380Z",
    //             created_at: "2022-10-30T16:21:26.380Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Shawn",
    //             taxNo: "71285288048",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 3,
    //         updated_at: "2022-10-30T16:22:00.869Z",
    //         created_at: "2022-10-30T16:22:00.869Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 38,
    //         dealerSiteId: 38,
    //         dealerSite: {
    //             id: 38,
    //             updated_at: "2022-10-30T16:21:51.928Z",
    //             created_at: "2022-10-30T16:21:51.928Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ms. Magali Green",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "nhkflvsvzm",
    //             externalDSCode: "hguvozryla",
    //             dealerId: 7,
    //             dealer: {
    //                 id: 7,
    //                 updated_at: "2022-10-30T16:21:27.552Z",
    //                 created_at: "2022-10-30T16:21:27.552Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Russ",
    //                 taxNo: "54570857757",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 38,
    //             updated_at: "2022-10-30T16:21:39.100Z",
    //             created_at: "2022-10-30T16:21:39.100Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Mr. Vaughn Little",
    //             taxNo: "73080712527",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "nhkflvsvzm",
    //         },
    //     },
    // },
    // {
    //     id: 33,
    //     updated_at: "2022-10-31T03:18:22.596Z",
    //     created_at: "2022-10-31T03:18:22.596Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 19,
    //     vds_rltn_id: 7,
    //     buyerSite: {
    //         id: 19,
    //         updated_at: "2022-10-30T16:22:00.850Z",
    //         created_at: "2022-10-30T16:22:00.448Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Gottlieb, Gottlieb and Gottlieb",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "sutnmzrlxe",
    //         externalDSCode: "emsqvhzjsa",
    //         externalBSCode: "rerum",
    //         buyer_id: 38,
    //         buyer: {
    //             id: 38,
    //             updated_at: "2022-10-30T16:21:43.075Z",
    //             created_at: "2022-10-30T16:21:43.075Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Marquis",
    //             taxNo: "80937524491",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 7,
    //         updated_at: "2022-10-30T16:22:10.483Z",
    //         created_at: "2022-10-30T16:22:10.483Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 48,
    //         dealerSiteId: 48,
    //         dealerSite: {
    //             id: 48,
    //             updated_at: "2022-10-30T16:22:00.823Z",
    //             created_at: "2022-10-30T16:22:00.823Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Gudrun Stark PhD",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "sutnmzrlxe",
    //             externalDSCode: "emsqvhzjsa",
    //             dealerId: 38,
    //             dealer: {
    //                 id: 38,
    //                 updated_at: "2022-10-30T16:21:41.868Z",
    //                 created_at: "2022-10-30T16:21:41.868Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Bulah",
    //                 taxNo: "91881421765",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 48,
    //             updated_at: "2022-10-30T16:21:42.542Z",
    //             created_at: "2022-10-30T16:21:42.542Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Mr. Jan Nolan II",
    //             taxNo: "30040797372",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "sutnmzrlxe",
    //         },
    //     },
    // },
    // {
    //     id: 32,
    //     updated_at: "2022-10-31T03:17:56.802Z",
    //     created_at: "2022-10-31T03:17:56.802Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 22,
    //     vds_rltn_id: 4,
    //     buyerSite: {
    //         id: 22,
    //         updated_at: "2022-10-30T16:22:04.050Z",
    //         created_at: "2022-10-30T16:22:04.050Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Kerluke-Kerluke",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "rxamfdtiyk",
    //         externalDSCode: "pwbohofqgj",
    //         externalBSCode: "atque",
    //         buyer_id: 81,
    //         buyer: {
    //             id: 81,
    //             updated_at: "2022-10-30T16:22:02.783Z",
    //             created_at: "2022-10-30T16:22:02.783Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ellen",
    //             taxNo: "44763027479",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 4,
    //         updated_at: "2022-10-30T16:22:06.229Z",
    //         created_at: "2022-10-30T16:22:06.229Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 50,
    //         dealerSiteId: 50,
    //         dealerSite: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:22:01.763Z",
    //             created_at: "2022-10-30T16:22:01.763Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Emery Blanda",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xjmouwxlda",
    //             externalDSCode: "gobwfcnysl",
    //             dealerId: 68,
    //             dealer: {
    //                 id: 68,
    //                 updated_at: "2022-10-30T16:21:51.135Z",
    //                 created_at: "2022-10-30T16:21:51.135Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Theresia",
    //                 taxNo: "67321135766",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:21:43.067Z",
    //             created_at: "2022-10-30T16:21:43.067Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Durward Metz DVM",
    //             taxNo: "73223944510",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xjmouwxlda",
    //         },
    //     },
    // },
    // {
    //     id: 31,
    //     updated_at: "2022-10-31T03:17:36.534Z",
    //     created_at: "2022-10-31T03:17:36.534Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 20,
    //     vds_rltn_id: 4,
    //     buyerSite: {
    //         id: 20,
    //         updated_at: "2022-10-30T16:22:01.784Z",
    //         created_at: "2022-10-30T16:22:01.784Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Hayes, Hayes and Hayes",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "xjmouwxlda",
    //         externalDSCode: "gobwfcnysl",
    //         externalBSCode: "quo",
    //         buyer_id: 68,
    //         buyer: {
    //             id: 68,
    //             updated_at: "2022-10-30T16:21:56.571Z",
    //             created_at: "2022-10-30T16:21:56.571Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Raleigh",
    //             taxNo: "80408761535",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 4,
    //         updated_at: "2022-10-30T16:22:06.229Z",
    //         created_at: "2022-10-30T16:22:06.229Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 50,
    //         dealerSiteId: 50,
    //         dealerSite: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:22:01.763Z",
    //             created_at: "2022-10-30T16:22:01.763Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Emery Blanda",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xjmouwxlda",
    //             externalDSCode: "gobwfcnysl",
    //             dealerId: 68,
    //             dealer: {
    //                 id: 68,
    //                 updated_at: "2022-10-30T16:21:51.135Z",
    //                 created_at: "2022-10-30T16:21:51.135Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Theresia",
    //                 taxNo: "67321135766",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:21:43.067Z",
    //             created_at: "2022-10-30T16:21:43.067Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Durward Metz DVM",
    //             taxNo: "73223944510",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xjmouwxlda",
    //         },
    //     },
    // },
    // {
    //     id: 35,
    //     updated_at: "2022-10-31T03:19:30.483Z",
    //     created_at: "2022-10-31T03:19:30.483Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 23,
    //     vds_rltn_id: 10,
    //     buyerSite: {
    //         id: 23,
    //         updated_at: "2022-10-30T16:22:04.446Z",
    //         created_at: "2022-10-30T16:22:04.446Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Powlowski Inc",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "vsofojamqz",
    //         externalDSCode: "nwwyrziqit",
    //         externalBSCode: "recusandae",
    //         buyer_id: 57,
    //         buyer: {
    //             id: 57,
    //             updated_at: "2022-10-30T16:21:51.911Z",
    //             created_at: "2022-10-30T16:21:51.911Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Reed",
    //             taxNo: "79962449614",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 10,
    //         updated_at: "2022-10-30T16:22:13.285Z",
    //         created_at: "2022-10-30T16:22:13.285Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 55,
    //         dealerSiteId: 55,
    //         dealerSite: {
    //             id: 55,
    //             updated_at: "2022-10-30T16:22:04.413Z",
    //             created_at: "2022-10-30T16:22:04.413Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Chaya Schowalter",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "vsofojamqz",
    //             externalDSCode: "nwwyrziqit",
    //             dealerId: 57,
    //             dealer: {
    //                 id: 57,
    //                 updated_at: "2022-10-30T16:21:47.841Z",
    //                 created_at: "2022-10-30T16:21:47.841Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Jacky",
    //                 taxNo: "10097810400",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 55,
    //             updated_at: "2022-10-30T16:21:44.348Z",
    //             created_at: "2022-10-30T16:21:44.348Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Jarrett Wisoky",
    //             taxNo: "26540849206",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "vsofojamqz",
    //         },
    //     },
    // },
    // {
    //     id: 39,
    //     updated_at: "2022-10-31T03:21:18.333Z",
    //     created_at: "2022-10-31T03:21:18.333Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 25,
    //     vds_rltn_id: 23,
    //     buyerSite: {
    //         id: 25,
    //         updated_at: "2022-10-30T16:22:07.296Z",
    //         created_at: "2022-10-30T16:22:07.296Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Friesen Group",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "qmxwzgzswv",
    //         externalDSCode: "bnpligrcbt",
    //         externalBSCode: "consequatur",
    //         buyer_id: 54,
    //         buyer: {
    //             id: 54,
    //             updated_at: "2022-10-30T16:21:50.567Z",
    //             created_at: "2022-10-30T16:21:50.567Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Sharon",
    //             taxNo: "33488046041",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 23,
    //         updated_at: "2022-10-30T16:22:39.622Z",
    //         created_at: "2022-10-30T16:22:39.622Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 57,
    //         dealerSiteId: 57,
    //         dealerSite: {
    //             id: 57,
    //             updated_at: "2022-10-30T16:22:07.271Z",
    //             created_at: "2022-10-30T16:22:07.271Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Cyrus King Sr.",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "qmxwzgzswv",
    //             externalDSCode: "bnpligrcbt",
    //             dealerId: 54,
    //             dealer: {
    //                 id: 54,
    //                 updated_at: "2022-10-30T16:21:47.288Z",
    //                 created_at: "2022-10-30T16:21:47.288Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Lewis",
    //                 taxNo: "96369239445",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 57,
    //             updated_at: "2022-10-30T16:21:44.620Z",
    //             created_at: "2022-10-30T16:21:44.620Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Christ Purdy DDS",
    //             taxNo: "83918467820",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "qmxwzgzswv",
    //         },
    //     },
    // },
    // {
    //     id: 43,
    //     updated_at: "2022-10-31T03:23:46.912Z",
    //     created_at: "2022-10-31T03:23:46.912Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 28,
    //     vds_rltn_id: 30,
    //     buyerSite: {
    //         id: 28,
    //         updated_at: "2022-10-30T16:22:08.955Z",
    //         created_at: "2022-10-30T16:22:08.955Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Hartmann Ltd",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "oqiuobchsj",
    //         externalDSCode: "hvsxxlhgtk",
    //         externalBSCode: "cupiditate",
    //         buyer_id: 50,
    //         buyer: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:21:48.461Z",
    //             created_at: "2022-10-30T16:21:48.461Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kendall",
    //             taxNo: "27626915181",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 30,
    //         updated_at: "2022-10-30T16:22:47.579Z",
    //         created_at: "2022-10-30T16:22:47.579Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 60,
    //         dealerSiteId: 60,
    //         dealerSite: {
    //             id: 60,
    //             updated_at: "2022-10-30T16:22:08.928Z",
    //             created_at: "2022-10-30T16:22:08.928Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Darlene Wolf",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "oqiuobchsj",
    //             externalDSCode: "hvsxxlhgtk",
    //             dealerId: 50,
    //             dealer: {
    //                 id: 50,
    //                 updated_at: "2022-10-30T16:21:46.298Z",
    //                 created_at: "2022-10-30T16:21:46.298Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Carissa",
    //                 taxNo: "58377676013",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 60,
    //             updated_at: "2022-10-30T16:21:45.601Z",
    //             created_at: "2022-10-30T16:21:45.601Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ms. Faye Zulauf PhD",
    //             taxNo: "46943646525",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "oqiuobchsj",
    //         },
    //     },
    // },
    // {
    //     id: 34,
    //     updated_at: "2022-10-31T03:19:06.157Z",
    //     created_at: "2022-10-31T03:19:06.157Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 31,
    //     vds_rltn_id: 9,
    //     buyerSite: {
    //         id: 31,
    //         updated_at: "2022-10-30T16:22:11.112Z",
    //         created_at: "2022-10-30T16:22:11.112Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Beahan-Beahan",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "szrfzgcwjz",
    //         externalDSCode: "gcitzidxpw",
    //         externalBSCode: "dolorem",
    //         buyer_id: 13,
    //         buyer: {
    //             id: 13,
    //             updated_at: "2022-10-30T16:21:32.072Z",
    //             created_at: "2022-10-30T16:21:32.072Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Darius",
    //             taxNo: "80022002045",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 9,
    //         updated_at: "2022-10-30T16:22:12.935Z",
    //         created_at: "2022-10-30T16:22:12.935Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 63,
    //         dealerSiteId: 63,
    //         dealerSite: {
    //             id: 63,
    //             updated_at: "2022-10-30T16:22:11.084Z",
    //             created_at: "2022-10-30T16:22:11.084Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Meta Marvin",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "szrfzgcwjz",
    //             externalDSCode: "gcitzidxpw",
    //             dealerId: 13,
    //             dealer: {
    //                 id: 13,
    //                 updated_at: "2022-10-30T16:21:33.119Z",
    //                 created_at: "2022-10-30T16:21:33.119Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Moriah",
    //                 taxNo: "89838273015",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 63,
    //             updated_at: "2022-10-30T16:21:46.071Z",
    //             created_at: "2022-10-30T16:21:46.071Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Karley Erdman",
    //             taxNo: "61969228535",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "szrfzgcwjz",
    //         },
    //     },
    // },
    // {
    //     id: 37,
    //     updated_at: "2022-10-31T03:20:21.496Z",
    //     created_at: "2022-10-31T03:20:21.496Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 32,
    //     vds_rltn_id: 20,
    //     buyerSite: {
    //         id: 32,
    //         updated_at: "2022-10-30T16:22:11.269Z",
    //         created_at: "2022-10-30T16:22:11.269Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Sporer Group",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "syjznjlnxz",
    //         externalDSCode: "qfhsjoebgy",
    //         externalBSCode: "cum",
    //         buyer_id: 2,
    //         buyer: {
    //             id: 2,
    //             updated_at: "2022-10-30T16:21:22.660Z",
    //             created_at: "2022-10-30T16:21:22.660Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kenny",
    //             taxNo: "38250207174",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 20,
    //         updated_at: "2022-10-30T16:22:34.747Z",
    //         created_at: "2022-10-30T16:22:34.747Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 64,
    //         dealerSiteId: 64,
    //         dealerSite: {
    //             id: 64,
    //             updated_at: "2022-10-30T16:22:11.248Z",
    //             created_at: "2022-10-30T16:22:11.248Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Greta Goldner",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "syjznjlnxz",
    //             externalDSCode: "qfhsjoebgy",
    //             dealerId: 2,
    //             dealer: {
    //                 id: 2,
    //                 updated_at: "2022-10-30T16:21:23.018Z",
    //                 created_at: "2022-10-30T16:21:23.018Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Kaley",
    //                 taxNo: "19148685510",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 64,
    //             updated_at: "2022-10-30T16:21:46.602Z",
    //             created_at: "2022-10-30T16:21:46.602Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Mr. Florian Gulgowski",
    //             taxNo: "64442068491",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "syjznjlnxz",
    //         },
    //     },
    // },
    // {
    //     id: 38,
    //     updated_at: "2022-10-31T03:20:52.797Z",
    //     created_at: "2022-10-31T03:20:52.797Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 37,
    //     vds_rltn_id: 21,
    //     buyerSite: {
    //         id: 37,
    //         updated_at: "2022-10-30T16:22:18.604Z",
    //         created_at: "2022-10-30T16:22:18.604Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Spinka, Spinka and Spinka",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "ecvckrfevs",
    //         externalDSCode: "xtqzbjzlry",
    //         externalBSCode: "eum",
    //         buyer_id: 54,
    //         buyer: {
    //             id: 54,
    //             updated_at: "2022-10-30T16:21:50.567Z",
    //             created_at: "2022-10-30T16:21:50.567Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Sharon",
    //             taxNo: "33488046041",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 21,
    //         updated_at: "2022-10-30T16:22:35.151Z",
    //         created_at: "2022-10-30T16:22:35.151Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 71,
    //         dealerSiteId: 71,
    //         dealerSite: {
    //             id: 71,
    //             updated_at: "2022-10-30T16:22:18.582Z",
    //             created_at: "2022-10-30T16:22:18.582Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Terrell Rogahn",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ecvckrfevs",
    //             externalDSCode: "xtqzbjzlry",
    //             dealerId: 54,
    //             dealer: {
    //                 id: 54,
    //                 updated_at: "2022-10-30T16:21:47.288Z",
    //                 created_at: "2022-10-30T16:21:47.288Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Lewis",
    //                 taxNo: "96369239445",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 71,
    //             updated_at: "2022-10-30T16:21:48.451Z",
    //             created_at: "2022-10-30T16:21:48.451Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Aubree Bechtelar",
    //             taxNo: "61533527124",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ecvckrfevs",
    //         },
    //     },
    // },
    // {
    //     id: 41,
    //     updated_at: "2022-10-31T03:22:19.648Z",
    //     created_at: "2022-10-31T03:22:19.648Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 41,
    //     vds_rltn_id: 25,
    //     buyerSite: {
    //         id: 41,
    //         updated_at: "2022-10-30T16:22:21.674Z",
    //         created_at: "2022-10-30T16:22:21.674Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Armstrong-Armstrong",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "wllqghtbjb",
    //         externalDSCode: "tmnmuyiobe",
    //         externalBSCode: "tempore",
    //         buyer_id: 111,
    //         buyer: {
    //             id: 111,
    //             updated_at: "2022-10-30T16:22:15.390Z",
    //             created_at: "2022-10-30T16:22:15.390Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Alexzander",
    //             taxNo: "64039215253",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 25,
    //         updated_at: "2022-10-30T16:22:40.740Z",
    //         created_at: "2022-10-30T16:22:40.740Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 75,
    //         dealerSiteId: 75,
    //         dealerSite: {
    //             id: 75,
    //             updated_at: "2022-10-30T16:22:21.645Z",
    //             created_at: "2022-10-30T16:22:21.645Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Leo Keebler",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "wllqghtbjb",
    //             externalDSCode: "tmnmuyiobe",
    //             dealerId: 111,
    //             dealer: {
    //                 id: 111,
    //                 updated_at: "2022-10-30T16:22:06.172Z",
    //                 created_at: "2022-10-30T16:22:06.172Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Robb",
    //                 taxNo: "67725830452",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 75,
    //             updated_at: "2022-10-30T16:21:49.414Z",
    //             created_at: "2022-10-30T16:21:49.414Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ms. Katrine Jacobson Jr.",
    //             taxNo: "10632996777",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "wllqghtbjb",
    //         },
    //     },
    // },
    // {
    //     id: 40,
    //     updated_at: "2022-10-31T03:21:48.110Z",
    //     created_at: "2022-10-31T03:21:48.110Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 47,
    //     vds_rltn_id: 24,
    //     buyerSite: {
    //         id: 47,
    //         updated_at: "2022-10-30T16:22:30.832Z",
    //         created_at: "2022-10-30T16:22:30.832Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Jast-Jast",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "fdwopgsuje",
    //         externalDSCode: "hdpjmkehlk",
    //         externalBSCode: "qui",
    //         buyer_id: 111,
    //         buyer: {
    //             id: 111,
    //             updated_at: "2022-10-30T16:22:15.390Z",
    //             created_at: "2022-10-30T16:22:15.390Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Alexzander",
    //             taxNo: "64039215253",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 24,
    //         updated_at: "2022-10-30T16:22:40.333Z",
    //         created_at: "2022-10-30T16:22:40.333Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 82,
    //         dealerSiteId: 82,
    //         dealerSite: {
    //             id: 82,
    //             updated_at: "2022-10-30T16:22:30.788Z",
    //             created_at: "2022-10-30T16:22:30.788Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Reuben Powlowski",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "fdwopgsuje",
    //             externalDSCode: "hdpjmkehlk",
    //             dealerId: 111,
    //             dealer: {
    //                 id: 111,
    //                 updated_at: "2022-10-30T16:22:06.172Z",
    //                 created_at: "2022-10-30T16:22:06.172Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Robb",
    //                 taxNo: "67725830452",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 82,
    //             updated_at: "2022-10-30T16:21:52.167Z",
    //             created_at: "2022-10-30T16:21:52.167Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Frederique Kuhn",
    //             taxNo: "50083883792",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "fdwopgsuje",
    //         },
    //     },
    // },
    // {
    //     id: 48,
    //     updated_at: "2022-10-31T03:25:57.424Z",
    //     created_at: "2022-10-31T03:25:57.424Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 53,
    //     vds_rltn_id: 44,
    //     buyerSite: {
    //         id: 53,
    //         updated_at: "2022-10-30T16:22:36.487Z",
    //         created_at: "2022-10-30T16:22:36.487Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Carter-Carter",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "uaktfqeirr",
    //         externalDSCode: "pwzqfwiqzf",
    //         externalBSCode: "magnam",
    //         buyer_id: 50,
    //         buyer: {
    //             id: 50,
    //             updated_at: "2022-10-30T16:21:48.461Z",
    //             created_at: "2022-10-30T16:21:48.461Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kendall",
    //             taxNo: "27626915181",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 44,
    //         updated_at: "2022-10-30T16:22:59.295Z",
    //         created_at: "2022-10-30T16:22:59.295Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 88,
    //         dealerSiteId: 88,
    //         dealerSite: {
    //             id: 88,
    //             updated_at: "2022-10-30T16:22:36.460Z",
    //             created_at: "2022-10-30T16:22:36.460Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kellen Stiedemann",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "uaktfqeirr",
    //             externalDSCode: "pwzqfwiqzf",
    //             dealerId: 50,
    //             dealer: {
    //                 id: 50,
    //                 updated_at: "2022-10-30T16:21:46.298Z",
    //                 created_at: "2022-10-30T16:21:46.298Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Carissa",
    //                 taxNo: "58377676013",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 88,
    //             updated_at: "2022-10-30T16:21:55.028Z",
    //             created_at: "2022-10-30T16:21:55.028Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Mr. Neal Prosacco",
    //             taxNo: "14474917736",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "uaktfqeirr",
    //         },
    //     },
    // },
    // {
    //     id: 42,
    //     updated_at: "2022-10-31T03:22:52.183Z",
    //     created_at: "2022-10-31T03:22:52.183Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 58,
    //     vds_rltn_id: 28,
    //     buyerSite: {
    //         id: 58,
    //         updated_at: "2022-10-30T16:22:38.863Z",
    //         created_at: "2022-10-30T16:22:38.863Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Hane-Hane",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "cgpjcdgxcc",
    //         externalDSCode: "jzbqqhpexj",
    //         externalBSCode: "quidem",
    //         buyer_id: 68,
    //         buyer: {
    //             id: 68,
    //             updated_at: "2022-10-30T16:21:56.571Z",
    //             created_at: "2022-10-30T16:21:56.571Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Raleigh",
    //             taxNo: "80408761535",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 28,
    //         updated_at: "2022-10-30T16:22:44.219Z",
    //         created_at: "2022-10-30T16:22:44.219Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 93,
    //         dealerSiteId: 93,
    //         dealerSite: {
    //             id: 93,
    //             updated_at: "2022-10-30T16:22:38.846Z",
    //             created_at: "2022-10-30T16:22:38.846Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ramona Bradtke",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "cgpjcdgxcc",
    //             externalDSCode: "jzbqqhpexj",
    //             dealerId: 68,
    //             dealer: {
    //                 id: 68,
    //                 updated_at: "2022-10-30T16:21:51.135Z",
    //                 created_at: "2022-10-30T16:21:51.135Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Theresia",
    //                 taxNo: "67321135766",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 93,
    //             updated_at: "2022-10-30T16:21:58.677Z",
    //             created_at: "2022-10-30T16:21:58.677Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Lempi Wunsch",
    //             taxNo: "69984559696",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "cgpjcdgxcc",
    //         },
    //     },
    // },
    // {
    //     id: 49,
    //     updated_at: "2022-10-31T03:26:30.229Z",
    //     created_at: "2022-10-31T03:26:30.229Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 60,
    //     vds_rltn_id: 45,
    //     buyerSite: {
    //         id: 60,
    //         updated_at: "2022-10-30T16:22:39.612Z",
    //         created_at: "2022-10-30T16:22:39.612Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Aufderhar-Aufderhar",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "xwojxmfclr",
    //         externalDSCode: "bucrltcshj",
    //         externalBSCode: "deserunt",
    //         buyer_id: 57,
    //         buyer: {
    //             id: 57,
    //             updated_at: "2022-10-30T16:21:51.911Z",
    //             created_at: "2022-10-30T16:21:51.911Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Reed",
    //             taxNo: "79962449614",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 45,
    //         updated_at: "2022-10-30T16:23:00.193Z",
    //         created_at: "2022-10-30T16:23:00.193Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 95,
    //         dealerSiteId: 95,
    //         dealerSite: {
    //             id: 95,
    //             updated_at: "2022-10-30T16:22:39.586Z",
    //             created_at: "2022-10-30T16:22:39.586Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Tomasa Jacobson PhD",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xwojxmfclr",
    //             externalDSCode: "bucrltcshj",
    //             dealerId: 57,
    //             dealer: {
    //                 id: 57,
    //                 updated_at: "2022-10-30T16:21:47.841Z",
    //                 created_at: "2022-10-30T16:21:47.841Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Jacky",
    //                 taxNo: "10097810400",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 95,
    //             updated_at: "2022-10-30T16:21:59.269Z",
    //             created_at: "2022-10-30T16:21:59.269Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Jessyca Koelpin DVM",
    //             taxNo: "71485223320",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xwojxmfclr",
    //         },
    //     },
    // },
    // {
    //     id: 44,
    //     updated_at: "2022-10-31T03:24:07.235Z",
    //     created_at: "2022-10-31T03:24:07.235Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 64,
    //     vds_rltn_id: 36,
    //     buyerSite: {
    //         id: 64,
    //         updated_at: "2022-10-30T16:22:44.385Z",
    //         created_at: "2022-10-30T16:22:44.385Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Dickinson and Sons",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "ewzvjlcyap",
    //         externalDSCode: "ykbkbgupcx",
    //         externalBSCode: "pariatur",
    //         buyer_id: 81,
    //         buyer: {
    //             id: 81,
    //             updated_at: "2022-10-30T16:22:02.783Z",
    //             created_at: "2022-10-30T16:22:02.783Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ellen",
    //             taxNo: "44763027479",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 36,
    //         updated_at: "2022-10-30T16:22:54.050Z",
    //         created_at: "2022-10-30T16:22:54.050Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 99,
    //         dealerSiteId: 99,
    //         dealerSite: {
    //             id: 99,
    //             updated_at: "2022-10-30T16:22:44.352Z",
    //             created_at: "2022-10-30T16:22:44.352Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Gaylord Donnelly IV",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ewzvjlcyap",
    //             externalDSCode: "ykbkbgupcx",
    //             dealerId: 81,
    //             dealer: {
    //                 id: 81,
    //                 updated_at: "2022-10-30T16:21:55.042Z",
    //                 created_at: "2022-10-30T16:21:55.042Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Davon",
    //                 taxNo: "50864669353",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 99,
    //             updated_at: "2022-10-30T16:22:00.167Z",
    //             created_at: "2022-10-30T16:22:00.167Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Wilmer Graham",
    //             taxNo: "51727338851",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ewzvjlcyap",
    //         },
    //     },
    // },
    // {
    //     id: 46,
    //     updated_at: "2022-10-31T03:25:00.375Z",
    //     created_at: "2022-10-31T03:25:00.375Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 70,
    //     vds_rltn_id: 42,
    //     buyerSite: {
    //         id: 70,
    //         updated_at: "2022-10-30T16:22:47.897Z",
    //         created_at: "2022-10-30T16:22:47.897Z",
    //         start_date: null,
    //         end_date: null,
    //         name: 'O"Reilly Ltd',
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "mylazndhlt",
    //         externalDSCode: "nxpwnykzza",
    //         externalBSCode: "ad",
    //         buyer_id: 150,
    //         buyer: {
    //             id: 150,
    //             updated_at: "2022-10-30T16:22:32.771Z",
    //             created_at: "2022-10-30T16:22:32.771Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Afton",
    //             taxNo: "84523177085",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 42,
    //         updated_at: "2022-10-30T16:22:57.620Z",
    //         created_at: "2022-10-30T16:22:57.620Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 105,
    //         dealerSiteId: 105,
    //         dealerSite: {
    //             id: 105,
    //             updated_at: "2022-10-30T16:22:47.876Z",
    //             created_at: "2022-10-30T16:22:47.876Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Denis Schmeler DVM",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "mylazndhlt",
    //             externalDSCode: "nxpwnykzza",
    //             dealerId: 150,
    //             dealer: {
    //                 id: 150,
    //                 updated_at: "2022-10-30T16:22:18.573Z",
    //                 created_at: "2022-10-30T16:22:18.573Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Ramiro",
    //                 taxNo: "58460863769",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 105,
    //             updated_at: "2022-10-30T16:22:01.463Z",
    //             created_at: "2022-10-30T16:22:01.463Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Virginia Rau",
    //             taxNo: "30856229575",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "mylazndhlt",
    //         },
    //     },
    // },
    // {
    //     id: 51,
    //     updated_at: "2022-10-31T03:27:20.563Z",
    //     created_at: "2022-10-31T03:27:20.563Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 71,
    //     vds_rltn_id: 61,
    //     buyerSite: {
    //         id: 71,
    //         updated_at: "2022-10-30T16:22:48.159Z",
    //         created_at: "2022-10-30T16:22:48.159Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Green, Green and Green",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "wxmncodlzv",
    //         externalDSCode: "iadmmntecv",
    //         externalBSCode: "quis",
    //         buyer_id: 2,
    //         buyer: {
    //             id: 2,
    //             updated_at: "2022-10-30T16:21:22.660Z",
    //             created_at: "2022-10-30T16:21:22.660Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kenny",
    //             taxNo: "38250207174",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 61,
    //         updated_at: "2022-10-30T16:23:10.859Z",
    //         created_at: "2022-10-30T16:23:10.859Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 106,
    //         dealerSiteId: 106,
    //         dealerSite: {
    //             id: 106,
    //             updated_at: "2022-10-30T16:22:48.136Z",
    //             created_at: "2022-10-30T16:22:48.136Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Donnell Turcotte",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "wxmncodlzv",
    //             externalDSCode: "iadmmntecv",
    //             dealerId: 2,
    //             dealer: {
    //                 id: 2,
    //                 updated_at: "2022-10-30T16:21:23.018Z",
    //                 created_at: "2022-10-30T16:21:23.018Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Kaley",
    //                 taxNo: "19148685510",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 106,
    //             updated_at: "2022-10-30T16:22:01.718Z",
    //             created_at: "2022-10-30T16:22:01.718Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Felicity Bernier",
    //             taxNo: "28408143504",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "wxmncodlzv",
    //         },
    //     },
    // },
    // {
    //     id: 45,
    //     updated_at: "2022-10-31T03:24:33.319Z",
    //     created_at: "2022-10-31T03:24:33.319Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 72,
    //     vds_rltn_id: 37,
    //     buyerSite: {
    //         id: 72,
    //         updated_at: "2022-10-30T16:22:49.025Z",
    //         created_at: "2022-10-30T16:22:49.025Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Stehr PLC",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "qwusyfskbo",
    //         externalDSCode: "djxvzzrkrd",
    //         externalBSCode: "accusantium",
    //         buyer_id: 48,
    //         buyer: {
    //             id: 48,
    //             updated_at: "2022-10-30T16:21:47.957Z",
    //             created_at: "2022-10-30T16:21:47.957Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Vicky",
    //             taxNo: "26963081411",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 37,
    //         updated_at: "2022-10-30T16:22:54.951Z",
    //         created_at: "2022-10-30T16:22:54.951Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 107,
    //         dealerSiteId: 107,
    //         dealerSite: {
    //             id: 107,
    //             updated_at: "2022-10-30T16:22:49.005Z",
    //             created_at: "2022-10-30T16:22:49.005Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Parker Hirthe Jr.",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "qwusyfskbo",
    //             externalDSCode: "djxvzzrkrd",
    //             dealerId: 48,
    //             dealer: {
    //                 id: 48,
    //                 updated_at: "2022-10-30T16:21:45.282Z",
    //                 created_at: "2022-10-30T16:21:45.282Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Benton",
    //                 taxNo: "69776156990",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 107,
    //             updated_at: "2022-10-30T16:22:01.887Z",
    //             created_at: "2022-10-30T16:22:01.887Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ephraim Moore",
    //             taxNo: "69322375835",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "qwusyfskbo",
    //         },
    //     },
    // },
    // {
    //     id: 52,
    //     updated_at: "2022-10-31T03:27:50.411Z",
    //     created_at: "2022-10-31T03:27:50.411Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 73,
    //     vds_rltn_id: 68,
    //     buyerSite: {
    //         id: 73,
    //         updated_at: "2022-10-30T16:22:49.410Z",
    //         created_at: "2022-10-30T16:22:49.410Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Wolf LLC",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "hbjhektceu",
    //         externalDSCode: "wruavkdhlp",
    //         externalBSCode: "sit",
    //         buyer_id: 38,
    //         buyer: {
    //             id: 38,
    //             updated_at: "2022-10-30T16:21:43.075Z",
    //             created_at: "2022-10-30T16:21:43.075Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Marquis",
    //             taxNo: "80937524491",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 68,
    //         updated_at: "2022-10-30T16:23:18.102Z",
    //         created_at: "2022-10-30T16:23:18.102Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 108,
    //         dealerSiteId: 108,
    //         dealerSite: {
    //             id: 108,
    //             updated_at: "2022-10-30T16:22:49.381Z",
    //             created_at: "2022-10-30T16:22:49.381Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Mr. Consuelo Sipes",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "hbjhektceu",
    //             externalDSCode: "wruavkdhlp",
    //             dealerId: 38,
    //             dealer: {
    //                 id: 38,
    //                 updated_at: "2022-10-30T16:21:41.868Z",
    //                 created_at: "2022-10-30T16:21:41.868Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Bulah",
    //                 taxNo: "91881421765",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 108,
    //             updated_at: "2022-10-30T16:22:02.039Z",
    //             created_at: "2022-10-30T16:22:02.039Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Talia Monahan",
    //             taxNo: "58842438076",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "hbjhektceu",
    //         },
    //     },
    // },
    // {
    //     id: 50,
    //     updated_at: "2022-10-31T03:26:55.157Z",
    //     created_at: "2022-10-31T03:26:55.157Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 79,
    //     vds_rltn_id: 60,
    //     buyerSite: {
    //         id: 79,
    //         updated_at: "2022-10-30T16:22:54.440Z",
    //         created_at: "2022-10-30T16:22:54.440Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Howe and Sons",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "xluqytybcz",
    //         externalDSCode: "crmutnsffo",
    //         externalBSCode: "quos",
    //         buyer_id: 11,
    //         buyer: {
    //             id: 11,
    //             updated_at: "2022-10-30T16:21:30.538Z",
    //             created_at: "2022-10-30T16:21:30.538Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Loma",
    //             taxNo: "11684172090",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 60,
    //         updated_at: "2022-10-30T16:23:10.627Z",
    //         created_at: "2022-10-30T16:23:10.627Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 114,
    //         dealerSiteId: 114,
    //         dealerSite: {
    //             id: 114,
    //             updated_at: "2022-10-30T16:22:54.419Z",
    //             created_at: "2022-10-30T16:22:54.419Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Malcolm Schiller",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xluqytybcz",
    //             externalDSCode: "crmutnsffo",
    //             dealerId: 11,
    //             dealer: {
    //                 id: 11,
    //                 updated_at: "2022-10-30T16:21:31.556Z",
    //                 created_at: "2022-10-30T16:21:31.556Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Brando",
    //                 taxNo: "65076097310",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 114,
    //             updated_at: "2022-10-30T16:22:04.001Z",
    //             created_at: "2022-10-30T16:22:04.001Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Dawn Wunsch",
    //             taxNo: "50362576361",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xluqytybcz",
    //         },
    //     },
    // },
    // {
    //     id: 47,
    //     updated_at: "2022-10-31T03:25:29.759Z",
    //     created_at: "2022-10-31T03:25:29.759Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 80,
    //     vds_rltn_id: 43,
    //     buyerSite: {
    //         id: 80,
    //         updated_at: "2022-10-30T16:22:54.937Z",
    //         created_at: "2022-10-30T16:22:54.937Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Quigley PLC",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "xvzkcvtrpa",
    //         externalDSCode: "xxhzctdrav",
    //         externalBSCode: "vel",
    //         buyer_id: 107,
    //         buyer: {
    //             id: 107,
    //             updated_at: "2022-10-30T16:22:12.263Z",
    //             created_at: "2022-10-30T16:22:12.263Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Kaitlyn",
    //             taxNo: "41039097909",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 43,
    //         updated_at: "2022-10-30T16:22:58.257Z",
    //         created_at: "2022-10-30T16:22:58.257Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 115,
    //         dealerSiteId: 115,
    //         dealerSite: {
    //             id: 115,
    //             updated_at: "2022-10-30T16:22:54.918Z",
    //             created_at: "2022-10-30T16:22:54.918Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Keara Olson",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xvzkcvtrpa",
    //             externalDSCode: "xxhzctdrav",
    //             dealerId: 107,
    //             dealer: {
    //                 id: 107,
    //                 updated_at: "2022-10-30T16:22:04.787Z",
    //                 created_at: "2022-10-30T16:22:04.787Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Danyka",
    //                 taxNo: "57155028005",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 115,
    //             updated_at: "2022-10-30T16:22:04.366Z",
    //             created_at: "2022-10-30T16:22:04.366Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Lazaro Berge",
    //             taxNo: "53991301901",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "xvzkcvtrpa",
    //         },
    //     },
    // },
    // {
    //     id: 53,
    //     updated_at: "2022-10-31T03:28:16.429Z",
    //     created_at: "2022-10-31T03:28:16.429Z",
    //     start_date: null,
    //     end_date: null,
    //     buyerSiteId: 86,
    //     vds_rltn_id: 70,
    //     buyerSite: {
    //         id: 86,
    //         updated_at: "2022-10-30T16:23:00.589Z",
    //         created_at: "2022-10-30T16:23:00.589Z",
    //         start_date: null,
    //         end_date: null,
    //         name: "Schumm-Schumm",
    //         attribute1: null,
    //         attribute2: null,
    //         attribute3: null,
    //         attribute4: null,
    //         attribute5: null,
    //         externalVCode: "ghfongqodm",
    //         externalDSCode: "orasiwdhip",
    //         externalBSCode: "rerum",
    //         buyer_id: 185,
    //         buyer: {
    //             id: 185,
    //             updated_at: "2022-10-30T16:22:48.992Z",
    //             created_at: "2022-10-30T16:22:48.992Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Greyson",
    //             taxNo: "61167548582",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //         },
    //     },
    //     vToDS: {
    //         id: 70,
    //         updated_at: "2022-10-30T16:23:20.254Z",
    //         created_at: "2022-10-30T16:23:20.254Z",
    //         start_date: null,
    //         end_date: null,
    //         vendorId: 121,
    //         dealerSiteId: 121,
    //         dealerSite: {
    //             id: 121,
    //             updated_at: "2022-10-30T16:23:00.569Z",
    //             created_at: "2022-10-30T16:23:00.569Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Shaina Leannon",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ghfongqodm",
    //             externalDSCode: "orasiwdhip",
    //             dealerId: 185,
    //             dealer: {
    //                 id: 185,
    //                 updated_at: "2022-10-30T16:22:30.950Z",
    //                 created_at: "2022-10-30T16:22:30.950Z",
    //                 start_date: null,
    //                 end_date: null,
    //                 name: "Noel",
    //                 taxNo: "38913858733",
    //                 attribute1: null,
    //                 attribute2: null,
    //                 attribute3: null,
    //                 attribute4: null,
    //                 attribute5: null,
    //             },
    //         },
    //         vendor: {
    //             id: 121,
    //             updated_at: "2022-10-30T16:22:07.507Z",
    //             created_at: "2022-10-30T16:22:07.507Z",
    //             start_date: null,
    //             end_date: null,
    //             name: "Ms. Summer Hintz III",
    //             taxNo: "74989944606",
    //             attribute1: null,
    //             attribute2: null,
    //             attribute3: null,
    //             attribute4: null,
    //             attribute5: null,
    //             externalVCode: "ghfongqodm",
    //         },
    //     },
    // },
];

//@ts-ignore
console.log(formater.advanceTransformer(obj));

export default formater;
